<?php
    $success = $block->getData('success');

    if (empty($success)) {
        $success = "none";
    } else {
        $success = $this->tableIt($success,"success");
    }


    $error = $block->getData('error');
    if (empty($error)) {
        $error = "none";
    } else {
        $error = $this->tableIt( $error, "error");
    }

    $errorDataFormat = $block->getData('errordataformat');    
?>

<style>
    .link { text-align: right; }
    
    .error-format {
        background: #ffdddd;
        border: 1px solid red;
        padding: 0.5rem;
        margin: 1.6rem 0;
    }
    
    table.tableit {
        min-width: 30%    
    }
    
    table.tableit tr:hover {background:#e0f6fe}
    table.tableit tr:last-child {display: none}
    table.tableit td {
        margin: 0.1rem;
        padding: 0.2rem 0.7rem;
        border:1px solid #303030;
    }
</style>

<div class="link"><a class="back" href="<?=$block->getData('form_url')?>">back</a></div>
<h2>Results</h2>
<?php if($errorDataFormat) { ?>
<div class="error-format"><?=$errorDataFormat?></div>
<?php } ?>
<div class="success">
    <h3>Correctly updated sku</h3>
    <?=($success)?>
</div>
<hr />   
<div class="error">
<h3>Errors</h3>
    <?=($error)?>
</div>

